Class dc.jrpereirajr.interop.adapter.climatiq.samples.SampleProduction Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="dc.jrpereirajr.interop.adapter.climatiq.samples.SampleProduction" TestingEnabled="true" LogGeneralTraceEvents="true">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="ClimatiqOperation" Category="" ClassName="dc.jrpereirajr.interop.adapter.climatiq.ClimatiqOperation" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="true" Schedule="">
    <Setting Target="Adapter" Name="ApiKey">A9G61KBCFJ4VCGJQ7GHH5FZJMNTG</Setting>
    <Setting Target="Adapter" Name="SSLConfig">ISC.FeatureTracker.SSL.Config</Setting>
  </Item>
</Production>
}

}
